theme: jekyll-theme-minimal

# Name of website
title: Puneet Thukral

baseurl: "/"


# --- Navigation bar options --- #

# List of links in the navigation bar
docs:

- title: JavaScript
  url: js.html

- title: Python
  url: py.html

- title: Agile
  url: agile.html

