theme: jekyll-theme-minimal

# Name of website
title: Puneet Thukral

baseurl: ""


# --- Navigation bar options --- #

# List of links in the navigation bar
docs:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html

