theme: jekyll-theme-hacker

# Name of website
title: Puneet Thukral

baseurl: ""


# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources: "/web"
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"


# --- Footer options --- #

